#ifndef __CMUI_UI_CLIENT_H__
#define __CMUI_UI_CLIENT_H__
#include "ccore/c_target.h"
#ifdef USE_PRAGMA_ONCE
#    pragma once
#endif

namespace ncore
{
    namespace nmui
    {
        // client maintains the following structures for the UI
        // - framebuffer: the pixel data for the UI, which is received from the server
        // - framestate:  the hash values for the framebuffer, used for detecting changes and optimizing updates
        // - input events: the events generated by the user, such as mouse clicks and keyboard input
        // - sensor data: the data from the sensors, such as temperature, humidity, pressure, light
        // - TCP socket: the connection with the server, used for sending input events, sensor data and
        //               receiving framebuffer updates

    }  // namespace nmui
}  // namespace ncore

#endif  /// __CMUI_UI_CLIENT_H__
